AppBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        task:

            type: string
            length: 255
        dueDate:
            type: datetime
    lifecycleCallbacks: {  }
