<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertSkilllRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkilllRepository extends \Doctrine\ORM\EntityRepository
{
}
