<?php

namespace OC\PlatformBundle\Repository;

use OC\PlatformBundle\Entity\Advert;

/**
 * AdvertSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends \Doctrine\ORM\EntityRepository
{


}

